(function(v,k){function y(){function n(){var e;e=k("amd");e.fork=n;return e}return n()}[].indexOf||(Array.prototype.indexOf=function(n,e,p){p=this.length;for(e=(p+~~e)%p;e<p&&(!(e in this)||this[e]!==n);e++);return e^p?e:-1});if("function"===typeof define&&define.amd)define(y);else{var w=function(){var n,e=[],p={};n=k("global");n.fork=w;n.noConflict=function(){var l,k;k=Array.prototype.slice.apply(arguments);for(l=0;l<e.length;l+=1)"undefined"===typeof p[e[l]]?delete v[e[l]]:v[e[l]]=p[e[l]];p={};
for(l=0;l<k.length;l+=1){if("string"!==typeof k[l])throw Error("Cannot replace namespaces. All new namespaces must be strings.");p[k[l]]=v[k[l]];v[k[l]]=n}return e=k};return n};w().noConflict("KeyboardJS","k")}})(this,function(){function v(){window.addEventListener?(document.addEventListener("keydown",y,!1),document.addEventListener("keyup",w,!1),window.addEventListener("blur",k,!1),window.addEventListener("webkitfullscreenchange",k,!1),window.addEventListener("mozfullscreenchange",k,!1)):window.attachEvent&&
(document.attachEvent("onkeydown",y),document.attachEvent("onkeyup",w),window.attachEvent("onblur",k))}function k(b){s=[];p();l(b)}function y(b){var a,c;a=n(b.keyCode);if(!(1>a.length)){for(c=0;c<a.length;c+=1)H(a[c]);for(a=0;a<r.length;a+=1)if(c=u(r[a][0]),-1===x.indexOf(r[a])&&z(c)){x.push(r[a]);for(c=0;c<r[a][1].length;c+=1)H(r[a][1][c])}var d,f,g,e,h,j=[];c=[].concat(s);for(a=0;a<q.length;a+=1)d=I(q[a].keyCombo).length,j[d]||(j[d]=[]),j[d].push(q[a]);for(d=j.length-1;0<=d;d-=1)if(j[d])for(a=0;a<
j[d].length;a+=1){f=j[d][a];bindingKeys=I(f.keyCombo);h=!0;for(g=0;g<bindingKeys.length;g+=1)if(-1===c.indexOf(bindingKeys[g])){h=!1;break}if(h&&z(f.keyCombo)){B.push(f);for(g=0;g<bindingKeys.length;g+=1)h=c.indexOf(bindingKeys[g]),-1<h&&(c.splice(h,1),g-=1);for(g=0;g<f.keyDownCallback.length;g+=1)!1===f.keyDownCallback[g](b,E(),f.keyCombo)&&(e=!0);!0===e&&(b.preventDefault(),b.stopPropagation())}}}}function w(b){var a,c;a=n(b.keyCode);if(!(1>a.length)){for(c=0;c<a.length;c+=1)F(a[c]);p();l(b)}}function n(b){return A[b]||
[]}function e(b){for(var a in A)if(A.hasOwnProperty(a)&&-1<A[a].indexOf(b))return a;return!1}function p(){var b,a;for(b=0;b<x.length;b+=1)if(a=u(x[b][0]),!1===z(a)){for(a=0;a<x[b][1].length;a+=1)F(x[b][1][a]);x.splice(b,1);b-=1}}function l(b){var a,c,d,f;for(a=0;a<B.length;a+=1)if(d=B[a],!1===z(d.keyCombo)){for(c=0;c<d.keyUpCallback.length;c+=1)!1===d.keyUpCallback[c](b,E(),d.keyCombo)&&(f=!0);!0===f&&(b.preventDefault(),b.stopPropagation());B.splice(a,1);a-=1}}function G(b,a){var c,d,f;b=u(b);a=
u(a);if(b.length!==a.length)return!1;for(c=0;c<b.length;c+=1){if(b[c].length!==a[c].length)return!1;for(d=0;d<b[c].length;d+=1){if(b[c][d].length!==a[c][d].length)return!1;for(f=0;f<b[c][d].length;f+=1)if(-1===a[c][d].indexOf(b[c][d][f]))return!1}}return!0}function z(b){var a,c,d,f,g=0,e,h;b=u(b);for(a=0;a<b.length;a+=1){h=!0;for(c=g=0;c<b[a].length;c+=1){d=[].concat(b[a][c]);for(f=g;f<s.length;f+=1)e=d.indexOf(s[f]),-1<e&&(d.splice(e,1),g=f);if(0!==d.length){h=!1;break}}if(h)return!0}return!1}function I(b){var a,
c,d=[];b=u(b);for(a=0;a<b.length;a+=1)for(c=0;c<b[a].length;c+=1)d=d.concat(b[a][c]);return d}function u(b){var a=0,c=0,d=!1,f=!1,g=[],e=[],h=[],j="";if("object"===typeof b&&"function"===typeof b.push)return b;if("string"!==typeof b)throw Error('Cannot parse "keyCombo" because its type is "'+typeof b+'". It must be a "string".');for(;" "===b.charAt(a);)a+=1;for(;;){if(" "===b.charAt(a)){for(;" "===b.charAt(a);)a+=1;d=!0}else if(","===b.charAt(a)){if(c||f)throw Error("Failed to parse key combo. Unexpected , at character index "+
a+".");f=!0;a+=1}else if("+"===b.charAt(a)){j.length&&(h.push(j),j="");if(c||f)throw Error("Failed to parse key combo. Unexpected + at character index "+a+".");c=!0;a+=1}else if(">"===b.charAt(a)){j.length&&(h.push(j),j="");h.length&&(e.push(h),h=[]);if(c||f)throw Error("Failed to parse key combo. Unexpected > at character index "+a+".");c=!0;a+=1}else if(a<b.length-1&&"!"===b.charAt(a)&&(">"===b.charAt(a+1)||","===b.charAt(a+1)||"+"===b.charAt(a+1)))j+=b.charAt(a+1),f=d=c=!1,a+=2;else if(a<b.length&&
"+"!==b.charAt(a)&&">"!==b.charAt(a)&&","!==b.charAt(a)&&" "!==b.charAt(a)){if(!1===c&&!0===d||!0===f)j.length&&(h.push(j),j=""),h.length&&(e.push(h),h=[]),e.length&&(g.push(e),e=[]);for(f=d=c=!1;a<b.length&&"+"!==b.charAt(a)&&">"!==b.charAt(a)&&","!==b.charAt(a)&&" "!==b.charAt(a);)j+=b.charAt(a),a+=1}else{a+=1;continue}if(a>=b.length){j.length&&h.push(j);h.length&&e.push(h);e.length&&g.push(e);break}}return g}function J(b){var a,c,d=[];if("string"===typeof b)return b;if("object"!==typeof b||"function"!==
typeof b.push)throw Error("Cannot stringify key combo.");for(a=0;a<b.length;a+=1){d[a]=[];for(c=0;c<b[a].length;c+=1)d[a][c]=b[a][c].join(" + ");d[a]=d[a].join(" > ")}return d.join(" ")}function E(){return[].concat(s)}function H(b){if(b.match(/\s/))throw Error("Cannot add key name "+b+" to active keys because it contains whitespace.");-1<s.indexOf(b)||s.push(b)}function F(b){var a=e(b);"91"===a||"92"===a?s=[]:s.splice(s.indexOf(b),1)}function K(b,a){if("string"!==typeof b)throw Error("Cannot register new locale. The locale name must be a string.");
if("object"!==typeof a)throw Error("Cannot register "+b+" locale. The locale map must be an object.");if("object"!==typeof a.map)throw Error("Cannot register "+b+" locale. The locale map is invalid.");a.macros||(a.macros=[]);C[b]=a}function L(b){if(b){if("string"!==typeof b)throw Error("Cannot set locale. The locale name must be a string.");if(!C[b])throw Error("Cannot set locale to "+b+" because it does not exist. If you would like to submit a "+b+" locale map for KeyboardJS please submit it at https://github.com/RobertWHurst/KeyboardJS/issues.");
A=C[b].map;r=C[b].macros;M=b}return M}var m={},C={},M,A,r,s=[],q=[],B=[],x=[],t,D;D={map:{3:["cancel"],8:["backspace"],9:["tab"],12:["clear"],13:["enter"],16:["shift"],17:["ctrl"],18:["alt","menu"],19:["pause","break"],20:["capslock"],27:["escape","esc"],32:["space","spacebar"],33:["pageup"],34:["pagedown"],35:["end"],36:["home"],37:["left"],38:["up"],39:["right"],40:["down"],41:["select"],42:["printscreen"],43:["execute"],44:["snapshot"],45:["insert","ins"],46:["delete","del"],47:["help"],91:"command windows win super leftcommand leftwindows leftwin leftsuper".split(" "),
92:"command windows win super rightcommand rightwindows rightwin rightsuper".split(" "),145:["scrolllock","scroll"],186:["semicolon",";"],187:["equal","equalsign","="],188:["comma",","],189:["dash","-"],190:["period","."],191:["slash","forwardslash","/"],192:["graveaccent","`"],219:["openbracket","["],220:["backslash","\\"],221:["closebracket","]"],222:["apostrophe","'"],48:["zero","0"],49:["one","1"],50:["two","2"],51:["three","3"],52:["four","4"],53:["five","5"],54:["six","6"],55:["seven","7"],
56:["eight","8"],57:["nine","9"],96:["numzero","num0"],97:["numone","num1"],98:["numtwo","num2"],99:["numthree","num3"],100:["numfour","num4"],101:["numfive","num5"],102:["numsix","num6"],103:["numseven","num7"],104:["numeight","num8"],105:["numnine","num9"],106:["nummultiply","num*"],107:["numadd","num+"],108:["numenter"],109:["numsubtract","num-"],110:["numdecimal","num."],111:["numdevide","num/"],144:["numlock","num"],112:["f1"],113:["f2"],114:["f3"],115:["f4"],116:["f5"],117:["f6"],118:["f7"],
119:["f8"],120:["f9"],121:["f10"],122:["f11"],123:["f12"]},macros:[["shift + `",["tilde","~"]],["shift + 1",["exclamation","exclamationpoint","!"]],["shift + 2",["at","@"]],["shift + 3",["number","#"]],["shift + 4",["dollar","dollars","dollarsign","$"]],["shift + 5",["percent","%"]],["shift + 6",["caret","^"]],["shift + 7",["ampersand","and","&"]],["shift + 8",["asterisk","*"]],["shift + 9",["openparen","("]],["shift + 0",["closeparen",")"]],["shift + -",["underscore","_"]],["shift + =",["plus","+"]],
["shift + (",["opencurlybrace","opencurlybracket","{"]],["shift + )",["closecurlybrace","closecurlybracket","}"]],["shift + \\",["verticalbar","|"]],["shift + ;",["colon",":"]],["shift + '",["quotationmark",'"']],["shift + !,",["openanglebracket","<"]],["shift + .",["closeanglebracket",">"]],["shift + /",["questionmark","?"]]]};for(t=65;90>=t;t+=1)D.map[t]=String.fromCharCode(t+32),D.macros.push(["shift + "+String.fromCharCode(t+32)+", capslock + "+String.fromCharCode(t+32),[String.fromCharCode(t)]]);
K("us",D);L("us");v();m.enable=v;m.disable=function(){k();window.removeEventListener?(document.removeEventListener("keydown",y,!1),document.removeEventListener("keyup",w,!1),window.removeEventListener("blur",k,!1),window.removeEventListener("webkitfullscreenchange",k,!1),window.removeEventListener("mozfullscreenchange",k,!1)):window.detachEvent&&(document.detachEvent("onkeydown",y),document.detachEvent("onkeyup",w),window.detachEvent("onblur",k))};m.activeKeys=E;m.on=function(b,a,c){var d={},f,g=
[],e,h;"string"===typeof b&&(b=u(b));for(e=0;e<b.length;e+=1){f={};h=J([b[e]]);if("string"!==typeof h)throw Error("Failed to bind key combo. The key combo must be string.");f.keyCombo=h;f.keyDownCallback=[];f.keyUpCallback=[];a&&f.keyDownCallback.push(a);c&&f.keyUpCallback.push(c);q.push(f);g.push(f)}d.clear=function(){var a;for(a=0;a<g.length;a+=1)q.splice(q.indexOf(g[a]),1)};d.on=function(a){var b={},c,d,e;if("string"!==typeof a)throw Error("Cannot bind callback. The event name must be a string.");
if("keyup"!==a&&"keydown"!==a)throw Error('Cannot bind callback. The event name must be a "keyup" or "keydown".');c=Array.prototype.slice.apply(arguments,[1]);for(d=0;d<c.length;d+=1)if("function"===typeof c[d])if("keyup"===a)for(e=0;e<g.length;e+=1)g[e].keyUpCallback.push(c[d]);else if("keydown"===a)for(e=0;e<g.length;e+=1)g[e].keyDownCallback.push(c[d]);b.clear=function(){var b,d;for(b=0;b<c.length;b+=1)if("function"===typeof c[b])if("keyup"===a)for(d=0;d<g.length;d+=1)g[d].keyUpCallback.splice(g[d].keyUpCallback.indexOf(c[b]),
1);else for(d=0;d<g.length;d+=1)g[d].keyDownCallback.splice(g[d].keyDownCallback.indexOf(c[b]),1)};return b};return d};m.clear=function(b){var a,c;for(a=0;a<q.length;a+=1)c=q[a],G(b,c.keyCombo)&&(q.splice(a,1),a-=1)};m.clear.key=function(b){var a,c,d;if(b)for(a=0;a<q.length;a+=1){d=q[a];for(c=0;c<d.keyCombo.length;c+=1)if(-1<d.keyCombo[kI].indexOf(b)){q.splice(a,1);a-=1;break}}else q=[]};m.locale=L;m.locale.register=K;m.macro=function(b,a){if("string"!==typeof b&&("object"!==typeof b||"function"!==
typeof b.push))throw Error("Cannot create macro. The combo must be a string or array.");if("object"!==typeof a||"function"!==typeof a.push)throw Error("Cannot create macro. The injectedKeys must be an array.");r.push([b,a])};m.macro.remove=function(b){var a;if("string"!==typeof b&&("object"!==typeof b||"function"!==typeof b.push))throw Error("Cannot remove macro. The combo must be a string or array.");for(mI=0;mI<r.length;mI+=1)if(a=r[mI],G(b,a[0])){F(a[1]);r.splice(mI,1);break}};m.key={};m.key.name=
n;m.key.code=e;m.combo={};m.combo.active=z;m.combo.parse=u;m.combo.stringify=J;return m});